; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip ; Arduino Release v3.3.7 based on ESP-IDF v5.5.2.260206
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36-1/platform-espressif32.zip ; Arduino Release v3.3.7 based on ESP-IDF v5.5.2
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; upload_protocol = espota
; upload_port = 192.168.50.183
; upload_flags =
;     --port=3232
upload_protocol = esptool
; board_build.arduino.memory_type = qio_opi

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

; board_upload.maximum_size = 4194304  ; 限制单个 bin 文件最大为 4MB
; board_build.filesystem = littlefs
; board_build.partitions = partitions.csv

lib_deps =
    SPI
    Wire
    
    lvgl@9.3
    bodmer/TFT_eSPI@^2.5.43
    bogde/HX711 @ 0.7.5
    lewisxhe/SensorLib@^0.4.0
    homespan/HomeSpan@^2.1.6
    adafruit/Adafruit NeoPixel@^1.15.2
   ; bblanchon/ArduinoJson@^6.21.4
build_flags =
  -Wcpp

  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

  -D LOG_LOCAL_LEVEL=3
  -D CORE_DEBUG_LEVEL=4

  -D DEBUG
  -D LV_CONF_SKIP
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_COLOR_DEPTH=16
  -D LV_MEM_SIZE="(128U * 1024U)"
  -D LV_DRAW_SW_CIRCLE_CACHE_SIZE=16
  -D LV_FONT_MONTSERRAT_28=1
  -D LV_FONT_MONTSERRAT_26=1

  -D USER_SETUP_LOADED=1              ; 定义用户设置已加载
  -D LV_USE_TFT_ESPI=1                ; 定义使用TFT_ESPI库
  -D GC9A01_DRIVER=1                  ; 定义屏幕驱动
  -D TFT_HEIGHT=240
  ; -D TFT_RGB_ORDER=TFT_BGR            ; 定义屏幕RGB顺序  TFT_BGR  TFT_RGB
  ; -D TFT_INVERSION_OFF=1               ; 定义屏幕 inversion
  -D TFT_HOR_RES=240                  ; 定义屏幕分辨率
  -D TFT_VER_RES=240                  ; 定义屏幕分辨率

  -D enc_input_debug=1

  -D enc_button_input_debug=1
  -D input_task_debug=1
  -D lv_hal_debug=1

lib_extra_dirs = 


build_src_filter =
  +<*>

[env:esp32s3_dial]
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = min_spiffs.csv

lib_deps =
  ${env.lib_deps}

build_flags =
  ${env.build_flags}
  -D esp32s3_dial=1

  -D encoder_button_enter_Pin=GPIO_NUM_42
  -D i2c_sda_Pin=GPIO_NUM_11
  -D i2c_scl_Pin=GPIO_NUM_12
  -D i2c_clock_Speed=400000

  -D EC35_A_Pin=GPIO_NUM_41
  -D EC35_B_Pin=GPIO_NUM_40
  -D TFT_MISO=-1                      ; 定义SPI引脚
  -D TFT_DC=4                         ; 数据/命令引脚
  -D TFT_MOSI=5                       ; SPI数据引脚
  -D TFT_SCLK=6                       ; SPI时钟引脚
  -D TFT_CS=7                         ; 片选引脚
  -D TFT_RST=8                        ; 复位引脚
  -D TOUCH_CS=-1                      ; 触摸屏片选引脚
  -D TFT_BL=9                         ; 背光引脚
  -D TFT_BACKLIGHT_ON=HIGH            ; 背光控制
  -D USE_HSPI_PORT
  -D SPI_FREQUENCY=40000000           ; Set SPI frequency
  -D SPI_READ_FREQUENCY=16000000




lib_extra_dirs = 
  ${env.lib_extra_dirs}

build_src_filter =
  ${env.build_src_filter}

[env:esp32s3_86_box]

board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = min_spiffs.csv


lib_deps =
  ${env.lib_deps}

build_flags =
  ${env.build_flags}
  -D esp32s3_86_box=1
  -D hx711_input_debug=1
  
  -D HX711_DO_Pin=12 
  -D HX711_SCK_Pin=13
  -D EC35_A_Pin=GPIO_NUM_46
  -D EC35_B_Pin=GPIO_NUM_45
  -D i2c_sda_Pin=47
  -D i2c_scl_Pin=48
  -D i2c_clock_Speed=400000
  
  -D TFT_MISO=-1                      ; 定义SPI引脚
  -D TFT_DC=38                         ; 数据/命令引脚
  -D TFT_MOSI=42                       ; SPI数据引脚
  -D TFT_SCLK=41                       ; SPI时钟引脚
  -D TFT_CS=39                         ; 片选引脚
  -D TFT_RST=40                        ; 复位引脚
  -D TOUCH_CS=-1                      ; 触摸屏片选引脚
  -D TFT_BL=21                         ; 背光引脚
  -D TFT_BACKLIGHT_ON=HIGH            ; 背光控制
  -D USE_HSPI_PORT
  -D SPI_FREQUENCY=40000000           ; Set SPI frequency
  -D SPI_READ_FREQUENCY=16000000

  