; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36-1/platform-espressif32.zip ; Arduino Release v3.3.7 based on ESP-IDF v5.5.2
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; upload_protocol = espota
; upload_port = 192.168.50.183
; upload_flags =
;     --port=3232
upload_protocol = esptool
; board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_upload.flash_size = 8MB
; board_upload.maximum_size = 4194304  ; 限制单个 bin 文件最大为 4MB
; board_build.filesystem = littlefs
; board_build.partitions = partitions.csv
board_build.partitions = min_spiffs.csv
lib_deps =
    SPI
    Wire
    
    lvgl@9.3
    lovyan03/LovyanGFX@^1.2.0
    bogde/HX711 @ 0.7.5
    lewisxhe/SensorLib@^0.4.0
    homespan/HomeSpan@^2.1.6
    adafruit/Adafruit NeoPixel@^1.15.2
   ; bblanchon/ArduinoJson@^6.21.4


build_flags =
  -Wcpp
  -D LV_COLOR_DEPTH=16
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_DISABLE_I2C_NG=0
  ; -D CONFIG_DISABLE_HAL_LOCKS=1
  
  -D ARDUINO_DISABLE_I2C
  -D LOG_LOCAL_LEVEL=3
  -D CORE_DEBUG_LEVEL=5

  -D DEBUG
  -D LV_CONF_SKIP
  -D LV_CONF_INCLUDE_SIMPLE

  -D LV_MEM_SIZE="(128U * 1024U)"
  -D LV_DRAW_SW_CIRCLE_CACHE_SIZE=16
  -D LV_FONT_MONTSERRAT_28=1
  -D LV_FONT_MONTSERRAT_26=1

  -D enc_input_debug=1
  -D hx711_input_debug=1
  -D enc_button_input_debug=1
  -D input_task_debug=1
  -D lv_hal_debug=1

  -D LGFX_M5_Dial=1
  -D encoder_button_enter_Pin=GPIO_NUM_42
  -D i2c_sda_Pin=GPIO_NUM_11
  -D i2c_scl_Pin=GPIO_NUM_12
  -D i2c_clock_Speed=400000
  ; -D LGFX_86_Box=1



lib_extra_dirs = 


build_src_filter =
  +<*>